# Python Practice Questions -I

1. Write a python code to take in an integer input and store it in a variable a.

In [ ]:
a = int(input())

5

2. Display a's typecast.

In [ ]:
print(type(a))

<class 'int'>

3. Print 'True' if a is greater than or equal to 5, 'False' otherwise.

In [ ]:
if(a>=5):
  print('True')
else:
  print('False')
#note here True is printed in the case of a = 5 and a > 5 and False if a < 5.

True

4. Take a string input of your name and store it as a list of separate letters.
 e.g. if your name is Rahul, take input of your name and store it in a list containing ['R','a','h','u','l']. Name the list as 'l'. Print 'l'.

In [ ]:
s = input()
l = list(s)
print(l)

Rahul
['R', 'a', 'h', 'u', 'l']

5. Take a string input and print all the unique letters of the string.(pass in your string as all lowercase) e.g: string: 'india', output: {'i','n','d','a'}

In [ ]:
i = input()
s = set(i)
print(s)

india
{'d', 'i', 'n', 'a'}

6. Print the sum of numbers from 1 to n where n is the input by the user.

In [ ]:
#Method1
n = int(input())
for i in range(1,n):
  n=n+i
print(n)

10
55

In [ ]:
#Method2
n = int(input())
a = int((n*(n+1))/2)
print(a)

10
55

7. Print all the even numbers between 1 to n where n is the input given by user.

In [ ]:
n = int(input())
for i in range(0,n,2):
  print(i)

13
0
2
4
6
8
10
12

8. Print all the numbers from n to 1 in reverse order. e.g.: let n = 10, output = 10 9 8 7 6 5 4 3 2 1

In [ ]:
n = int(input())
for i in range(n,0,-1):
  print(i)

20
20
19
18
17
16
15
14
13
12
11
10
9
8
7
6
5
4
3
2
1

9. A factorial of a number is defined as n! = n*(n-1)*(n-2)*(n-3)*....*1. Write a python code to display factorial of a number n.

In [ ]:
n=int(input())
for i in range(n-1,0,-1):
  n=n*i
print(n)

5
120

10. Print multiplication table of an integer n. 
- n x 1 = n
- n x 2 = 2n
- 
- 
- so on... till 10.

In [ ]:
n = int(input())
for i in range(1, 11):
   print(n, 'x', i, '=', n*i)

12
12 x 1 = 12
12 x 2 = 24
12 x 3 = 36
12 x 4 = 48
12 x 5 = 60
12 x 6 = 72
12 x 7 = 84
12 x 8 = 96
12 x 9 = 108
12 x 10 = 120

11. Simple interest formula is given by:
Simple Interest = (P x T x R)/100

Write a python code to take in input of P, T and R and calculate the Simple Interest by defining a function sint

In [ ]:
def sint(p,t,r): 
    si = (p * t * r)/100
    print('The Simple Interest is', si)
6
p = int(input('Principal: '))
t = int(input('Time: '))
r = int(input('Rate of Interest: '))
sint(p, t, r)

Principal: 8
Time: 6
Rate of Interest: 8
The Simple Interest is 3.84

12. Find out if the number n is prime or not.

In [ ]:
n = int(input())
if n > 1:
  
    # Iterate from 2 to sqrt(n)
    for i in range(2, int((n)**0.5)+1):
        if (n % i) == 0:
            print(n, "is not a prime number")
            break
    else:
        print(n, "is a prime number")
  
else:
    print(n, "is not a prime number")

39323
39323 is a prime number

13. Find the maximum integer from an array of integers

In [ ]:
n = int(input('Size of aray: '))
arr = []
for i in range(n):
  arr.append(int(input()))
max = arr[0]
for i in range(1, n):
    if arr[i] > max:
        max = arr[i]
print ("Largest integer in given array is",max)

Size of aray: 5
12
14
23
89
45
Largest integer in given array is 89

14. Swap the first and last elements of a list.

In [ ]:
orig_list = []

size = len(orig_list)
  
temp = orig_list[0]
orig_list[0] = orig_list[size - 1]
orig_list[size - 1] = temp
print(orig_list)

[24, 35, 9, 56, 12]

15. Reverse the string "Hello World"

In [ ]:
txt = "Hello World"
txt = txt[::-1]
print(txt)

dlroW olleH

16. Write a program to accept a string from the user and display characters that are present at an even index number. e.g. If input is "Python", print P,t,o

In [ ]:
word = input()
size = len(word)
for i in range(0, size - 1, 2):
    print(word[i])

Python
P
t
o

17. Write a program to remove characters from a string starting from zero up to n and return a new string with the remaining letters.

In [ ]:
word = input()
n = int(input())
word = word[n:]
print(word)

Slicing
4
ing

18. From a given list of numbers print only those numbers which are divisible by 5

In [ ]:
num_list = [100, 25, 33, 49, 53, 40, 75]
for num in num_list:
    if num % 5 == 0:
        print(num)

100
25
40
75

  19. Print the following pattern.

  1

  2 2

  3 3 3

  4 4 4 4 

  5 5 5 5 5

In [ ]:
for num in range(6):
    for i in range(num):
        print (num, end=" ") 
    print("\n")

1

2 2

3 3 3

4 4 4 4

5 5 5 5 5

20. Given a two list of numbers, write a program to create a new list such that the new list should contain odd numbers from the first list and even numbers from the second list.

In [ ]:
def merge_list(list1, list2):
    result_list = []
    for num in list1:
        if num % 2 != 0:
            result_list.append(num)
    for num in list2:
        if num % 2 == 0:
            result_list.append(num)
    return result_list
list1 = [11, 20, 25, 32, 37]
list2 = [40, 47, 62, 75, 80]
print("result list:", merge_list(list1, list2))

result list: [11, 25, 37, 40, 62, 80]

21. Print the following pattern for 8 lines.

![image.png]()

In [ ]:
for i in range(9, 0, -1):
    for j in range(0, i - 1):
        print("*", end=' ')
    print(" ")

* * * * * * * *
* * * * * * *
* * * * * *
* * * * *
* * * *
* * *
* *
*

22. Write a Python program to convert them into a dictionary in a way that item from list1 is the key and item from list2 is the value.

list1 = ['India', 'USA', 'China']

list2 = [1, 2, 3]

In [ ]:
list1 = ['India', 'USA', 'China']
list2 = [1, 2, 3]

res_dict = dict(zip(list1, list2))
print(res_dict)

{'India': 1, 'USA': 2, 'China': 3}

23. Merge 2 dictionaries into 1.
- dict1 = {'India': 1, 'USA': 2, 'China': 3}
- dict2 = {'UK': 4, 'Japan': 5, 'Russia': 6}

In [ ]:
dict1 = {'India': 1, 'USA': 2, 'China': 3}
dict2 = {'UK': 4, 'Japan': 5, 'Russia': 6}
dict3 = {**dict1, **dict2}
print(dict3)

{'India': 1, 'USA': 2, 'China': 3, 'UK': 4, 'Japan': 5, 'Russia': 6}

24. Check if a value exists in a dictionary or not.
- sample_dict = {'India': 1, 'USA': 2, 'China': 3}
- check if 2 exists in the dictionary or not and print "2 present in dictionary" if it exists.

In [ ]:
sample_dict = {'India': 1, 'USA': 2, 'China': 3}
if 2 in sample_dict.values():
    print('2 present in dictionary')

2 present in dictionary

25. Get the key of a minimum value from the following dictionary.
 - sample_dict = {'India': 19, 'USA': 27, 'China': 76}

In [ ]:
sample_dict = {'India': 19, 'USA': 27, 'China': 76}
print(min(sample_dict, key=sample_dict.get))

India

26. Check if two sets have any elements in common. If yes, display the common elements
- set1 = {10, 20, 30, 40, 50}
- set2 = {60, 70, 80, 90, 10}

In [ ]:
set1 = {10, 20, 30, 40, 50}
set2 = {60, 70, 80, 90, 10}

if set1.isdisjoint(set2):
  print("No items in common")
else:
  print(set1.intersection(set2))

{10}

27. Remove items from set1 that are not common to both set1 and set2
- set1 = {10, 20, 30, 40, 50}
- set2 = {60, 70, 80, 90, 10}

In [ ]:
set1 = {10, 20, 30, 40, 50}
set2 = {30, 40, 50, 60, 70}

set1.intersection_update(set2)
print(set1)

{40, 50, 30}

28. Turn every item of a list into its square.

In [ ]:
numbers = [1, 2, 3, 4, 5, 6, 7,8,9,10]
res = []
for i in numbers:
    res.append(i * i)
print(res)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

29. Write a program that takes a number and checks whether it is a palindrome or not.

In [ ]:
n=int(input())
temp=n
rev=0
while(n>0):
    dig=n%10
    rev=rev*10+dig
    n=n//10
if(temp==rev):
    print("The number is a palindrome")
else:
    print("The number isn't a palindrome")

121
The number is a palindrome

30. A positive 3-digit integer is called an Armstrong number if sum of cubes of all digits of the number = the number. e.g: 153 = 1^3 + 5^3 + 3^3. 
Write a program to check if a 3-digit number is an Armstrong Number.

In [ ]:
n = int(input(""))
sum = 0
temp = n
while temp > 0:
   digit = temp % 10
   sum += digit ** 3
   temp //= 10
if n == sum:
   print(n,"is an Armstrong number")
else:
   print(n,"is not an Armstrong number")

153
153 is an Armstrong number

31. The Fibonacci Sequence is a series of numbers. The next number is found by adding up the two numbers before it. The first two numbers are 0 and 1.

For example, 0, 1, 1, 2, 3, 5,8,13. The next number in this series above is 8+13 = 21
Print first 9 terms of the Fibonacci series.

In [ ]:
num1 = 0
num2 = 1

print("Fibonacci sequence:")
for i in range(9):
    print(num1, end="  ")
    res = num1 + num2
    num1 = num2
    num2 = res

Fibonacci sequence:
0  1  1  2  3  5  8  13  21

32. Write a python code to convert celsius to farenheit scale.

In [ ]:
celsius_1 = float(input("Temperature value in degree Celsius: " ))  
Fahrenheit_1 = (celsius_1 * 1.8) + 32     
print('%.2f degree Celsius is equal to: %.2f Fahrenheit' %(celsius_1, Fahrenheit_1))

Temperature value in degree Celsius: 32
32.00 degree Celsius is equal to: 89.60 Fahrenheit

33. Write a program to find distance between 2 points (x1,y1) and (x2,y2)

In [ ]:
m = [6, 7]
n = [3, 11]
distance = (((m[0]-n[0])**2)+((m[1]-n[1])**2))**0.5

print(distance)

5.0

35. Given is a nested tuple. Write a program to modify the first item (30) of a list inside the following tuple to 300.

In [ ]:
tuple1 = (11, [30, 33], 44, 55)
tuple1[1][0] = 300
print(tuple1)

(11, [300, 33], 44, 55)

36. Reverse a given integer number
e.g: input: 5619, output: 9165

In [ ]:
num = int(input())
reverse_number = 0
print("Given Number ", num)
while num > 0:
    reminder = num % 10
    reverse_number = (reverse_number * 10) + reminder
    num = num // 10
print("Revere Number ", reverse_number)

5619
Given Number  5619
Revere Number  9165

37. Print the following pattern.

![image.png]()

In [ ]:
for i in range(0, 5):
    for j in range(0, i + 1):
        print("*", end=' ')
    print("\r")

for i in range(5, 0, -1):
    for j in range(0, i - 1):
        print("*", end=' ')
    print("\r")

*
* *
* * *
* * * *
* * * * *
* * * *
* * *
* *
*

38. Return the count of a given substring from a string.

In [ ]:
string = "India is a developing country. India is a democracy"
# use count method of a str class
cnt = string.count("India")
print(cnt)

2

39. Count the number of vowels in the given string.

In [ ]:
a=input().lower()
count=0
for x in a:
   if x=='a' or x=='e' or x=='i' or x=='o' or x=='u':
       count+=1
print(count)

typewriter
3

40. Calculate salary of an employee. 

- If their score>5 salary = salary + score x 0.1 x salary
- If thei score<=5, salary = salary + score x 0.05 x salary

In [ ]:
score=int(input('Enter score\n'))
salary=int(input('Enter your salary\n'))
if score>5:
        salary=salary+score*0.1*salary
else:
        salary=salary+score*0.05*salary

print('Your salary=',salary)

Enter score
7
Enter your salary
20000
Your salary= 34000.0

41. Find the roots of a quadratic equation defined by a.x^2 + b.x + c = 0

In [ ]:
print('Quadratic equation is of the form ax**2 + bx + c = 0')
a = int(input('a='))
b = int(input('b='))
c = int(input('c='))

x = b**2-4*a*c
root1 = (-b+x**0.5)/2*a
root2 = (-b-x**0.5)/2*a
print('The roots are',root1,',',root2)

Quadratic equation is of the form ax**2 + bx + c = 0
a=1
b=5
c=6
The roots are -2.0 , -3.0

42. Find the number of times all the letters in the strings occur.

In [ ]:
def find_duplicate():
    x =input("Enter a word = ")
    for char in set(x):
        counts=x.count(char)
        print(char,counts)
find_duplicate()

Enter a word = hello
o 1
h 1
e 1
l 2

43. Rotate a given array by 3 units to the left.

In [ ]:
def rotateArray(arr, n, d):
    temp = []
    i = 0
    while (i < d):
        temp.append(arr[i])
        i = i + 1
    i = 0
    while (d < n):
        arr[i] = arr[d]
        i = i + 1
        d = d + 1
    arr[:] = arr[: i] + temp
    return arr

arr = [1, 2, 3, 4, 5, 6, 7]
print("Array after left rotation is: ", end=' ')
print(rotateArray(arr, len(arr), 3))

Array after left rotation is:  [4, 5, 6, 7, 1, 2, 3]

44. Sort a tuple of tuples by 2nd item.

tuple1 = (('a', 23), ('b', 37), ('c', 11), ('d', 29))

In [ ]:
tuple1 = (('a', 23), ('b', 37), ('c', 11), ('d', 29))
tuple1 = tuple(sorted(list(tuple1), key=lambda x: x[1]))
print(tuple1)

(('c', 11), ('a', 23), ('d', 29), ('b', 37))

45. Check if all items in the tuple are the same

In [ ]:
def check(t):
    return all(i == t[0] for i in t)

tuple1 = (45, 45, 45, 45)
print(check(tuple1))

True

46. Display all the numbers from -20 to -1

In [ ]:
for num in range(-20, 0, 1):
    print(num)

-20
-19
-18
-17
-16
-15
-14
-13
-12
-11
-10
-9
-8
-7
-6
-5
-4
-3
-2
-1

47. Return a set of elements present in Set A or B, but not both

In [ ]:
set1 = {10, 20, 30, 40, 50}
set2 = {30, 40, 50, 60, 70}
print(set1.symmetric_difference(set2))

{20, 70, 10, 60}

48. Define a function circle to calculate area of a circle.

In [ ]:
def circle():
  pi = 3.14
  r = int(input())
  S = pi*(r**2)
  print('The area of the circle is: ',S)
circle()

10
The area of the circle is:  314.0

49. Write a recursive function to calculate the sum of numbers from 0 to 15

In [ ]:
def addition(num):
    if num:
        return num + addition(num - 1)
    else:
        return 0

res = addition(15)
print(res)

120

50. Find LCM of the 2 given numbers.

In [ ]:
def compute_lcm(x, y):
   if x > y:
       greater = x
   else:
       greater = y

   while(True):
       if((greater % x == 0) and (greater % y == 0)):
           lcm = greater
           break
       greater += 1

   return lcm

num1 = int(input())
num2 = int(input())

print("The L.C.M. is", compute_lcm(num1, num2))

15
17
The L.C.M. is 255

# Python Practice Questions -2

#### 1.Python program to interchange first and last elements in a list

In [ ]:
def swapList(newList):
     
    newList[0], newList[-1] = newList[-1], newList[0]
 
    return newList
     
# Driver code
newList = [12, 35, 9, 56, 24]
print(swapList(newList))

#### 2.Python program to swap two elements in a list

In [ ]:
def swapPositions(list, pos1, pos2):
     
    list[pos1], list[pos2] = list[pos2], list[pos1]
    return list
 
# Driver function
List = [23, 65, 19, 90]
pos1, pos2  = 1, 3
 
print(swapPositions(List, pos1-1, pos2-1))

#### 3.Find the length of list

In [ ]:
a = []
a.append("Data")
a.append("is ")
a.append("vital")
a.append("noted")
print("The length of list is: ", len(a))

#### 4.Reversing a List in Python

In [ ]:
def Reverse(lst):
    new_lst = lst[::-1]
    return new_lst
      
lst = [10, 11, 12, 13, 14, 15]
print(Reverse(lst))

#### 5. Copying a list

In [ ]:
def Cloning(li1):
    li_copy =[]
    li_copy = li1.copy()
    return li_copy
  

li1 = [4, 8, 2, 10, 15, 18]
li2 = Cloning(li1)
print("Original List:", li1)
print("After Cloning:", li2)

#### 6.Count occurrences of an element in a list

In [ ]:
def countX(lst, x):
    return lst.count(x)
 
# Driver Code
lst = [8, 6, 8, 10, 8, 20, 10, 8, 8]
x = 8
print('{} has occurred {} times'.format(x, countX(lst, x)))

#### 7.Find sum and average of List in Python

In [ ]:
L = [4, 5, 1, 2, 9, 7, 10, 8]
  
#using sum() method
count = sum(L)
  
#finding average
avg = count/len(L)
  
print("sum = ", count)
print("average = ", avg)

#### 8.Sum of  all number in List

In [ ]:
l=[1,2,4,5,6,7,8,9]
a=0
for c in l:
    a=a+c
print('sum is -->',a)

#### 9.Take list from user and do Product of all number in list

In [ ]:
l=[]
a=int(input('number of digit'))
for c in range(1,a+1):
    a=int(input('enter digit'))
    l.append(c)

t=1
for i in l:
    print(l)
    t=t*i
    print(t)

#### 10.Python program to find smallest number in a list

In [ ]:
list1 = [10, 20, 4, 45, 99]
 
print("Smallest element is:", min(list1))

#### 11.Python program to find largest number in a list

In [ ]:
list1 = [10, 20, 4, 45, 99]
  
  
#printing the maximum element
print("Largest element is:", max(list1))

#### 12.Python program to print even numbers in a list

In [ ]:
list1 = [10, 21, 4, 45, 66, 93]
 
# iterating each number in list
for num in list1:
 
    # checking condition
    if num % 2 == 0:
        print(num, end=" ")

#### 13.Python program to print odd numbers in a List

In [ ]:
list1 = [10, 21, 4, 45, 66, 93]
  
# iterating each number in list
for num in list1:
      
    # checking condition
    if num % 2 != 0:
       print(num, end = " ")

#### 14.Program to print duplicates from a list of integers

In [ ]:
l=[1,1,1,2,3,4,5,6,7,6,6,8,9,0,67,87,78,78]
for c in l:
    if(l.count(c)>1):
        print(c)

#### 15.Python program to count positive and negative numbers in a list

In [ ]:
list1 = [10, -21, 4, -45, 66, -93, 1]
  
pos_count, neg_count = 0, 0
  
# iterating each number in list
for num in list1:
      
    # checking condition
    if num >= 0:
        pos_count += 1
  
    else:
        neg_count += 1
          
print("Positive numbers in the list: ", pos_count)
print("Negative numbers in the list: ", neg_count)

#### 16.Remove multiple elements from a list in Python

In [ ]:
list1 = [11, 5, 17, 18, 23, 50]
 
# Iterate each element in list
# and add them in variable total
for ele in list1:
    if ele % 2 == 0:
        list1.remove(ele)
 
# printing modified list
print("New list after removing all even numbers: ", lis

#### 17.Python program to print all Prime numbers in an Interval

In [ ]:
start = 11
end = 25
 
for i in range(start, end+1):
    if i > 1:
        for j in range(2, i):
            if(i % j == 0):
                break
        else:
            print(i)

#### 18.Python program to check whether a number is Prime or not

In [ ]:
num =int(input('enter the number'))
  
# If given number is greater than 1
if num > 1:
  
    # Iterate from 2 to n / 2
    for i in range(2, int(num/2)+1):
  
        # If num is divisible by any number between
        # 2 and n / 2, it is not prime
        if (num % i) == 0:
            print(num, "is not a prime number")
            break
    else:
        print(num, "is a prime number")
else:
    print(num, "is not a prime number")

#### 19.Python Program for n-th Fibonacci number

In [ ]:
def Fibonacci(n):
    if n<= 0:
        print("Incorrect input")
    # First Fibonacci number is 0
    elif n == 1:
        return 0
    # Second Fibonacci number is 1
    elif n == 2:
        return 1
    else:
        return Fibonacci(n-1)+Fibonacci(n-2)
 
# Driver Program
 
print(Fibonacci(10))

#### 20.Python Program for How to check if a given number is Fibonacci number?
* A number is Fibonacci if and only if one or both of (5*n2 + 4) or (5*n2 – 4) is a perfect square

In [ ]:
import math
 
# A utility function that returns true if x is perfect square
def isPerfectSquare(x):
    s = int(math.sqrt(x))
    return s*s == x
 
# Returns true if n is a Fibinacci Number, else false
def isFibonacci(n):
 
    # n is Fibinacci if one of 5*n*n + 4 or 5*n*n - 4 or both
    # is a perferct square
    return isPerfectSquare(5*n*n + 4) or isPerfectSquare(5*n*n - 4)
    
# A utility function to test above functions
for i in range(1,11):
    if (isFibonacci(i) == True):
            print(i,"is a Fibonacci Number")
    else:
            print( i,"is a not Fibonacci Number ")

#### 21.Python Program for cube sum of first n natural numbers

In [ ]:
def sumOfSeries(n):
    sum = 0
    for i in range(1, n+1):
        sum +=i*i*i
          
    return sum
  
   
# Driver Function
n = 5
print(sumOfSeries(n)

#### 22.Python Program for Sum of squares of first n natural numbers

In [ ]:
def squaresum(n) :
  
    # Iterate i from 1 
    # and n finding 
    # square of i and
    # add to sum.
    sm = 0
    for i in range(1, n+1) :
        sm = sm + (i * i)
      
    return sm
  
# Driven Program
n = 4
print(squaresum(n))

#### 23.Python program to check if a string is palindrome or not

In [ ]:
def isPalindrome(s):
    return s == s[::-1]
 
 
# Driver code
s = "malayalam"
ans = isPalindrome(s)
 
if ans:
    print("Yes")
else:
    print("No")

#### 24.Python program to check whether the string is Symmetrical or Palindrome

In [ ]:
def rev_sentence(sentence): 
  
    # first split the string into words 
    words = sentence.split(' ') 
  
    # then reverse the split string list and join using space 
    reverse_sentence = ' '.join(reversed(words)) 
  
    # finally return the joined string 
    return reverse_sentence 
  
input = 'Data is Vital '
print (rev_sentence(input))

#### 25.How to remove i’th character from string in Python

In [ ]:
# Initializing String 
test_str = "Data is Vital"
  
# Printing original string 
print ("The original string is : " + test_str)
  
# Removing char at pos 3
# using loop
new_str = ""
  
for i in range(len(test_str)):
    if i != 2:
        new_str = new_str + test_str[i]
  
# Printing string after removal  
print ("The string after removal of i'th character : " + new_str)

#### 26.Write code to Check if a Substring is Present in a Given String

In [ ]:
def check(string, sub_str):
    if (string.find(sub_str) == -1):
        print("NO")
    else:
        print("YES")
            
# driver code
string = 'Data is Vital in Datascience'
sub_str ="Vital"
check(string, sub_str)

#### 27.Convert Snake case to Pascal case
**example :** 
* Input--> data_is_vital
* Output-> DataIsVital

**title()**
* : Used to convert the first character in each word to Uppercase and remaining characters to Lowercase in the string and returns a new string.

In [ ]:
# initializing string
test_str = 'convert_the_string'
  
# printing original string
print("The original string is : " + test_str)
  
# Convert Snake case to Pascal case
# Using title() + replace()
res = test_str.replace("_", " ").title().replace(" ", "")
  
# printing result 
print("The String after changing case : " + str(res))

#### 28.Find length of a string

In [ ]:
str = "Datascience"
print(len(str))

#### 29.Python program to print even length words in a string
* Input: s = "This is a python language"
* Output: This
          is
          python
          language

In [ ]:
def printWords(s):
      
    # split the string 
    s = s.split(' ') 
      
    # iterate in words of string 
    for word in s: 
          
        # if length is even 
        if len(word)%2==0:
            print(word) 
  
  
# Driver Code 
s = "i am Datascientist" 
printWords(s)

### 30.Python code to remove all duplicates from a given string in Python

In [ ]:
def removeDuplicate(str):
    s=set(str)
    s="".join(s)
    print("Without Order:",s)
    t=""
    for i in str:
        if(i in t):
            pass
        else:
            t=t+i
        print("With Order:",t)
      
str="Dataisvital"
removeDuplicate(str)

#### 31.Python program for removing i-th character from a string

In [ ]:
def remove(string, i): 
  
    for j in range(len(string)):
        if j == i:
            string = string.replace(string[i], "", 1)
    return string
      
      
string = "Data is i vital"
      
# Remove nth index eleme
    
    
# Print the new string
print(remove(string, 8))

#### 32.Check if a given string is binary string or not

In [ ]:
# Python program to check
# if a string is binary or not
 
# function for checking the
# string is accepted or not
def check(string) :
 
    # set function convert string
    # into set of characters .
    p = set(string)
 
    # declare set of '0', '1' .
    s = {'0', '1'}
 
    # check set p is same as set s
    # or set p contains only '0'
    # or set p contains only '1'
    # or not, if any one condition
    # is true then string is accepted
    # otherwise not .
    if s == p or p == {'0'} or p == {'1'}:
        print("Yes")
    else :
        print("No")

string='0101010'
check(string)

#### 33.Python code to  Extract Unique values dictionary values

In [ ]:
test_dict = {'gfg' : [5, 6, 7, 8],
             'is' : [10, 11, 7, 5],
             'best' : [6, 12, 10, 8],
             'for' : [1, 2, 5]}
  
# printing original dictionary
print("The original dictionary is : " + str(test_dict))
  
# Extract Unique values dictionary values
# Using set comprehension + values() + sorted()
res = list(sorted({ele for val in test_dict.values() for ele in val}))
  
# printing result 
print("The unique values list is : " + str(res))

#### 34.Python code to Merge two Dictionaries

In [ ]:
def Merge(dict1, dict2):
    return(dict2.update(dict1))
     
# Driver code
dict1 = {'a': 10, 'b': 8}
dict2 = {'d': 6, 'c': 4}
 
# This return None
print(Merge(dict1, dict2))
 
# changes made in dict2
print(dict2)

#### 35.Program to accept the strings which contains all vowels

In [ ]:
def check(string):
    if len(set(string.lower()).intersection("aeiou")) >= 5:
        return ('accepted')
    else:
        return ("not accepted")
 
 
# Driver code

string = "DataisVital"
print(check(string))

#### 36.Python Program to find sum of list

In [ ]:
l= []
  
# input values to list
l = [12, 3, 4, 15]
  
# sum() is an inbuilt function in python that adds 
# all the elements in list,set and tuples and returns
# the value 
ans = sum(l)
  
# display sum
print ('Sum of the array is ',ans)


#### 37.Print all  elements from the list using for loop

In [ ]:
l=[1,2,3,4,5,6,7,8,9,10]
for i in l:
    print(i)

#### 38.Adding multiple element at a time, in list

In [ ]:
l=[]
l.extend([1,2,3,5,6,7,8])
l

#### 39.Program to print ASCII Value of a character
**ord()** 
 * It converts the given string of length one, returns an integer representing the Unicode code point of the character. For example, ord(‘a’) returns the integer 97.

In [ ]:
c = 'g'
# print the ASCII value of assigned character in c
print("The ASCII value of '" + c + "' is", ord(c))

#### 40.Python code to  to clear a list

In [ ]:
list1 = [6, 0, 4, 1]
print('list1 before clear:', list1) 
  
# Clearing list 
list1.clear() 
print('list1 after clear:', list1)

#### 41.Python program to get Current Time

In [ ]:
from datetime import datetime
  
# Time object containing 
# the current time.
time = datetime.now().time() 
  
print("Current Time =", time)

#### 42.Get Current Date and Time using Python

In [ ]:
import datetime 
    
# using now() to get current time 
current_time = datetime.datetime.now() 
    
# Printing value of now. 
print ("Time now at india is : "
                                    , end = "") 
print (current_time)

#### 43.Python program to find yesterday’s, today’s and tomorrow’s date

In [ ]:
from datetime import datetime, timedelta
  
  
# Get today's date
presentday = datetime.now() # or presentday = datetime.today()
  
# Get Yesterday
yesterday = presentday - timedelta(1)
  
# Get Tomorrow
tomorrow = presentday + timedelta(1)
  
  
# strftime() is to format date according to
# the need by converting them to string
print("Yesterday = ", yesterday.strftime('%d-%m-%Y'))
print("Today = ", presentday.strftime('%d-%m-%Y'))
print("Tomorrow = ", tomorrow.strftime('%d-%m-%Y'))

#### 44.Python program to find difference between current time and given time

In [ ]:
def difference(h1, m1, h2, m2):
      
    # convert h1 : m1 into
    # minutes
    t1 = h1 * 60 + m1
      
    # convert h2 : m2 into
    # minutes 
    t2 = h2 * 60 + m2
      
    if (t1 == t2): 
        print("Both are same times")
        return 
    else:
          
        # calculating the difference
        diff = t2-t1
          
    # calculating hours from
    # difference
    h = (int(diff / 60)) % 24
    m = diff % 60
  
    print(h, ":", m)
  

      
    
    
difference(7, 20, 9, 45)
difference(15, 23, 18, 54)
difference(16, 20, 16, 20)

#### 45.Python program to find the area of a triangle whose sides are given

In [ ]:
import math
a = float(input("Enter the length of side a: "))
b = float(input("Enter the length of side b: "))
c = float(input("Enter the length of side c: "))
s = (a+b+c)/2
area = math.sqrt(s*(s-a)*(s-b)*(s-c))
print(" Area of the triangle is: ", area)

#### 46.Python program to find out the average of a set of integers

In [ ]:
count = int(input("Enter the count of numbers: "))
i = 0
sum = 0
for i in range(count):
    x = int(input("Enter an integer: "))
    sum = sum + x
avg = sum/count
print(" The average is: ", avg)

#### 47. Python program to display the given integer in reverse manner

In [ ]:
number = int(input("Enter a positive integer: "))
rev = 0
while(number!=0):
    digit = number%10
    rev = (rev*10)+digit
    number = number//10
print(rev)

#### 48.Python program to find the sum of the digits of an integer using while loop

In [ ]:
sum = 0
number = int(input("Enter an integer: "))
while(number!=0):
    digit = number%10
    sum = sum+digit
    number = number//10
print("Sum of digits is: ", sum)

#### 49.Python program to display all the multiples of 3 within the range 10 to 50

In [ ]:
for i in range(10,50):
    if (i%3==0):
        print(i)

#### 50.Python program to implement linear search

In [ ]:
numbers = [4,2,7,1,8,3,6]
f = 0 #flag
x = int(input("Enter the number to be found out: "))
for i in range(len(numbers)):
    if (x==numbers[i]):
        print(" Successful search, the element is found at position", i)
        f = 1
        break
if(f==0):
    print("Oops! Search unsuccessful")

# Python Practice Questions -3

1. Python program to convert the temperature in degree centigrade to Fahrenheit

In [ ]:
c = input(" Enter temperature in Centigrade: ")
f = (9*(int(c))/5)+32
print(" Temperature in Fahrenheit is: ", f)

 Enter temperature in Centigrade: 45
 Temperature in Fahrenheit is:  113.0

2. Python program to find the area of a triangle whose sides are given

In [ ]:
from math import sqrt
a = float(input("Enter the length of side a: "))
b = float(input("Enter the length of side b: "))
c = float(input("Enter the length of side c: "))
s = (a+b+c)/2
area = sqrt(s*(s-a)*(s-b)*(s-c))
print(" Area of the triangle is: ", area)

Enter the length of side a: 3
Enter the length of side b: 4
Enter the length of side c: 5
 Area of the triangle is:  6.0

3. Python program to find out the average of a set of integers

In [ ]:
count = int(input("Enter the count of numbers: "))
i = 0
sum = 0
for i in range(count):
    x = int(input("Enter an integer: "))
    sum = sum + x
avg = sum/count
print(" The average is: ", avg)

Enter the count of numbers: 4
Enter an integer: 2
Enter an integer: 2
Enter an integer: 3
Enter an integer: 4
 The average is:  2.75

4. Python program to find the product of a set of real numbers

In [ ]:
i = 0
product = 1
count = int(input("Enter the number of real numbers: "))
for i in range(count):
    x = float(input("Enter a real number: "))
    product = product * x
print("The product of the numbers is: ", product)

Enter the number of real numbers: 2
Enter a real number: 3
Enter a real number: 4
The product of the numbers is:  12.0

5. Python program to check whether the given integer is a multiple of 5

In [ ]:
number = int(input("Enter an integer: "))
if(number%5==0):
    print(number, "is a multiple of 5")
else:
    print(number, "is not a multiple of 5")

6. Python program to check whether the given integer is a multiple of both 5 and 7

In [ ]:
number = int(input("Enter an integer: "))
if((number%5==0)and(number%7==0)):
    print(number, "is a multiple of both 5 and 7")
else:
    print(number, "is not a multiple of both 5 and 7")

7. Python program to display the given integer in reverse manner

In [ ]:
number = int(input("Enter a positive integer: "))
rev = 0
while(number!=0):
    digit = number%10
    rev = (rev*10)+digit
    number = number//10
print(rev)

8. Python program to find the sum of the digits of an integer using while loop

In [ ]:
sum = 0
number = int(input("Enter an integer: "))
while(number!=0):
    digit = number%10
    sum = sum+digit
    number = number//10
print("Sum of digits is: ", sum)

9. Python program to display all the multiples of 3 within the range 10 to 50

In [ ]:
for i in range(10,50):
    if (i%3==0):
        print(i)

10. Python program to display all integers within the range 100-200 whose sum of digits is an even number

In [ ]:
for i in range(100,200):
    num = i
    sum = 0
    while(num!=0):
        digit = num%10
        sum = sum + digit
        num = num//10
    if(sum%2==0):
        print(i)

11. Python program to generate the prime numbers from 1 to N

In [ ]:
num =int(input("Enter the range: "))
for n in range(1,num):
    for i in range(2,n):
        if(n%i==0):
            break
    else:
        print(n)

12. Python program to find the odd numbers in the list

In [ ]:
numbers = [8,3,1,6,2,4,5,9]
count = 0
for i in range(len(numbers)):
    if(numbers[i]%2!=0):
        count = count+1
print("The number of odd numbers in the list are: ", count)

13. Python program to find the largest number in a list without using built-in functions

In [ ]:
numbers = [3,8,1,7,2,9,5,4]
big = numbers[0]
position = 0
for i in range(len(numbers)):
    if (numbers[i]>big):
        big = numbers[i]
        position = i
print("The largest element is ",big," which is found at position ",position)

14. Python program to insert a number to any position in a list

In [ ]:
numbers = [3,4,1,9,6,2,8]
print(numbers)
x = int(input("Enter the number to be inserted: "))
y = int(input("Enter the position: "))
numbers.insert(y,x)
print(numbers)

15. Python program to delete an element from a list by index

In [ ]:
numbers = [3,4,1,9,6,2,8]
print(numbers)
x = int(input("Enter the position of the element to be deleted: "))
numbers.pop(x)
print(numbers)

16. Python program to check whether a string is palindrome or not

In [ ]:
def rev(inputString):
    return inputString[::-1]
def isPalindrome(inputString):
    reverseString = rev(inputString)
    if (inputString == reverseString):
        return True
    return False
s = input("Enter a string: ")
result = isPalindrome(s)
if result == 1:
    print("The string is palindrome")
else:
    print("The string is not palindrome")

17. Write a Python program to extend a list without append()/extend().

In [ ]:
x = [10, 20, 30]
y = [40, 50, 60]
x[:0] =y
print(x)

18. Python program to printsquare pattern with * symbols

In [ ]:
n=int(input('Enter No Of Rows:'))
for i in range(n):
    print('* '*n)

19. Python program to print square pattern with digit in every row

In [ ]:
#n=int(input('Enter No Of Rows:'))
#for i in range(n):
#    print((str(i+1)+' ')*n)
    
rows = int(input('Enter No Of Rows:'))
for i in range(1, rows + 1):
    for j in range(1, rows + 1):
        if j <= i:
            print(i, end=' ')
        else:
            print(j, end=' ')
    print()

20. Python program to print Pyramid pattern with + symbols

In [ ]:
n=int(input('Enter Number of rows:'))
for i in range(n):
 print((' '*(n-i-1))+ ('+ ')*(i+1))

21. Python program to compare two strings and find out which has more characters

In [ ]:
s1=input("Enter first string:")
s2=input("Enter Second string:")
if s1==s2:
 print("Both strings are equal")
elif s1<s2:
 print("First String is less than Second String")
else:
 print("First String is greater than Second String")

22, Python program to replace a part of string with another

In [ ]:
a = "Hi my name is Balaji"
b = a.replace("Hi","Hello,")
b

23. Python program to call the last element of the list by using the len() function.

In [ ]:
gift_list=['socks', '4K drone', 'wine', 'jam']
# Type your code here.

index_no = len(gift_list)-1

ans_1 = gift_list[index_no]


print(ans_1)

24. Python program to return the count of a given substring from a string

In [ ]:
str_1 = "Emma is good developer. Emma is a writer"
# use count method of a str class
cnt = str_1.count("Emma")
print(cnt)

25. Python program to arrange string characters such that lowercase letters should come first

In [ ]:
str1 = "PYnAtivE"
print('Original String:', str1)
lower = []
upper = []
for char in str1:
    if char.islower():
        # add lowercase characters to lower list
        lower.append(char)
    else:
        # add uppercase characters to lower list
        upper.append(char)

# Join both list
sorted_str = ''.join(lower + upper)
print('Result:', sorted_str)

26. Python program to split a given string on hyphens and display each substring

In [ ]:
str1 = "Emma-is-a-data-scientist"
print("Original String is:", str1)

# split string
sub_strings = str1.split("-")

print("Displaying each substring")
for sub in sub_strings:
    print(sub)

27. Remove empty strings from a list of strings

In [ ]:
str_list = ["Emma", "Jon", "", "Kelly", None, "Eric", ""]
res_list = []
for s in str_list:
    # check for non empty string
    if s:
        res_list.append(s)
print(res_list)

28. Remove special symbols / punctuation from a string

In [ ]:
str1 = 'I am 25 years and 10 months old'
print("Original string is", str1)

# Retain Numbers in String
# Using list comprehension + join() + isdigit()
res = "".join([item for item in str1 if item.isdigit()])

print(res)

29. Find words with both alphabets and numbers

In [ ]:
str1 = "Emma25 is Data scientist50 and AI Expert"
print("The original string is : " + str1)

res = []
# split string on whitespace
temp = str1.split()

# Words with both alphabets and numbers
# isdigit() for numbers + isalpha() for alphabets
# use any() to check each character

for item in temp:
    if any(char.isalpha() for char in item) and any(char.isdigit() for char in item):
        res.append(item)

print("Displaying words with alphabets and numbers")
for i in res:
    print(i)

30. Python program to print a calendar for a given month (Jan 2008)

In [ ]:
import calendar

cal = calendar.month(2008, 1)
print("Here is the calendar:")
print("\n")
print(cal)

31. Python program to swap the case: upper to lower / lower to upper case

In [ ]:
str = "this is string example....wow!!!";
print(str.swapcase())

str = "THIS IS STRING EXAMPLE....WOW!!!";
print(str.swapcase())

32. Create a tuple "cardinal_numbers" with "first", "second" and "third" and get the 2nd cardinal number.

In [ ]:
cardinal_numbers = ("first", "second", "third")
print(cardinal_numbers[1])

second

33. Concatenate two strings together

In [ ]:

string_left = "Butter"
string_right = "fly"
print(string_left + string_right)

Butterfly

34. Display two strings together, with a space in between

In [ ]:
string_one = "Data"
string_two = "Science"
print(string_one + " " + string_two)

Data Science

In [ ]:
35. Python program to change the case of the strings

In [ ]:
string1 = "DATA"
string2 = "SCIENCE"

print(string1.lower())
print(string2.lower())

print("\n")

string1 = "python"
string2 = "program"
print(string1.upper())
print(string2.upper())

data
science


PYTHON
PROGRAM

36. Use of srtip() function.

In [ ]:
string1 = "    Filet Mignon"
string2 = "Brisket    "
string3 = "  Cheeseburger   "

print(string1.strip())  # Could also use .lstrip()
print(string1.strip())  # Could also use .rstrip()
print(string3.strip())

Filet Mignon
Filet Mignon
Cheeseburger

37. Python program to check if the given string starts with the given letters.

In [ ]:
string1 = "Data"
string2 = "data"
string3 = " dare"
string4 = "dimond"

print(string1.startswith("da")) # string1 starts with upper case.. 
print(string2.startswith("da"))
print(string3.startswith("da")) # string3 starts with space
print(string4.startswith("da"))

False
True
False
False

In [ ]:
string1 = "Becomes"
string2 = "becomes"
string3 = "BEAR"
string4 = "  bEautiful"

string1 = string1.lower()
# (string2 will pass unmodified)
string3 = string3.lower()
string4 = string4.strip().lower()

print(string1.startswith("be"))
print(string2.startswith("be"))
print(string3.startswith("be"))
print(string4.startswith("be"))

True
True
True
True

38. Return the upper-case of first letter entered by the user

In [ ]:
user_input = input("Tell me your password: ")
first_letter = user_input[0]
print("The first letter you entered was: " + first_letter.upper())

Tell me your password: dgfyd
The first letter you entered was: D

39. Get input from user, change it to upper case and get the length of the string

In [ ]:
my_input = input("Type something: ")
print(my_input)
print(my_input.upper())
print(len(my_input))

Type something: jhdhsfgdgh
jhdhsfgdgh
JHDHSFGDGH
10

40. Get two numbers from the user, multiply them and display the result

In [ ]:
a = input("Enter a number: ")
b = input("Enter another number: ")

# convert the input to float                       # or to integer using 'int()'
product = float(a) * float(b)


print("The product of " + a + " and " + b + " is " + str(product) + ".")

Enter a number: 4
Enter another number: 5
The product of 4 and 5 is 20.0.

41. Display all the factors of a number chosen by the user

In [ ]:
num = int(input("Enter a positive integer: "))
for divisor in range(1, num + 1):
    if num % divisor == 0:
        print(f"{divisor} is a factor of {num}")

Enter a positive integer: 45
1 is a factor of 45
3 is a factor of 45
5 is a factor of 45
9 is a factor of 45
15 is a factor of 45
45 is a factor of 45

42. Run in an infinite loop until the user types "s" or "S"

In [ ]:
while True:
    user_input = input('Type "s" or "S" to stop: ')
    if user_input.upper() == "S":
        break

Type "s" or "S" to stop: sds
Type "s" or "S" to stop: sxas
Type "s" or "S" to stop: axsx
Type "s" or "S" to stop: axasx
Type "s" or "S" to stop: s

43. Display every number from 1 through 30 except multiples of 3

In [ ]:
for i in range(1, 31):
    if i % 3 == 0:
        continue
    print(i)

1
2
4
5
7
8
10
11
13
14
16
17
19
20
22
23
25
26
28
29

44. Write a function to get the cube of a given number.

In [ ]:
def cube(num):
    """Returns the cube of the input number."""
    cube_num = num ** 3        # Could also use pow() by giving as pow(num, 3)
    return cube_num

In [ ]:
cube(5)

125

45. Write a function to print the given statement along with the input passed in the function

In [ ]:
def greet(name):
      print(f"Hello {name}!")

In [ ]:
greet("Guys")

Hello Guys!

46. Create a dictionary and update it by adding elements in it and print the updated dictionary

In [ ]:
person = {"name": "Jessa", 'country': "USA", "telephone": 1178}

# update dictionary by adding 2 new keys
person["weight"] = 50
person.update({"height": 6})

# print the updated dictionary
print(person)

{'name': 'Jessa', 'country': 'USA', 'telephone': 1178, 'weight': 50, 'height': 6}

47. Check whether the 'country' key exists and prints its value if found.

In [ ]:
person = {'name': 'Jessa', 'country': 'USA', 'telephone': 1178}

# Get the list of keys and check if 'country' key is present
key_name = 'country'
if key_name in person.keys():
    print("country name is", person[key_name])
else:
    print("Key not found")
# Output country name is USA

country name is USA

48. create more dictionaries and merge them into one.

In [ ]:
student_dict1 = {'Aadya': 1, 'Arul': 2, }
student_dict2 = {'Harry': 5, 'Olivia': 6}
student_dict3 = {'Nancy': 7, 'Perry': 9}

# join three dictionaries 
student_dict = {**student_dict1, **student_dict2, **student_dict3}
# printing the final Merged dictionary
print(student_dict)
# Output {'Aadya': 1, 'Arul': 2, 'Harry': 5, 'Olivia': 6, 'Nancy': 7, 'Perry': 9}

{'Aadya': 1, 'Arul': 2, 'Harry': 5, 'Olivia': 6, 'Nancy': 7, 'Perry': 9}

49. Write a Python program to return a new set with unique items from both sets by removing duplicates.

In [ ]:
set1 = {10, 20, 30, 40, 50}
set2 = {30, 40, 50, 60, 70}
print(set1.union(set2))

{70, 40, 10, 50, 20, 60, 30}

50. Write a Python program to remove items 10, 20, 30 from the following set at once.

In [ ]:
# difference_update() method removes the unwanted items from the original set
set1 = {10, 20, 30, 40, 50}
set1.difference_update({10, 20, 30})
print(set1)

{40, 50}

In [ ]:
# example:2

# difference_update() method also used to removes the items that exist in both sets.


x = {"apple", "banana", "cherry"}
y = {"google", "microsoft", "apple"}

x.difference_update(y)

print(x)

{'cherry', 'banana'}

# Python Practice Questions -4

1. Write a Python program to print the following string in a specific format (see the output).
Sample String : "Twinkle, twinkle, little star, How I wonder what you are! Up above the world so high, Like a diamond in the sky. Twinkle, twinkle, little star, How I wonder what you are" Output :

Twinkle, twinkle, little star,
	How I wonder what you are! 
		Up above the world so high,   		
		Like a diamond in the sky. 
Twinkle, twinkle, little star, 
	How I wonder what you are

In [ ]:
print("Twinkle, twinkle, little star, \n\tHow I wonder what you are! \n\t\tUp above the world so high, \n\t\tLike a diamond in the sky. \nTwinkle, twinkle, little star, \n\tHow I wonder what you are!")

2. Write a Python program to get the Python version you are using

In [ ]:
import sys
print("Python version")
print (sys.version)
print("Version info.")
print (sys.version_info)

3. Write a Python program to display the current date and time.

In [ ]:
import datetime
now = datetime.datetime.now()
print ("Current date and time : ",now)

4. Write a Python program which accepts the radius of a circle from the user and compute the area

In [ ]:
import numpy as np
def areaofcircle():
    radius=float(input('Enter the radius of Circle:'))
    area=np.pi *radius*radius
    return area

In [ ]:
areaofcircle()

5. Write a Python program which accepts the user's first and last name and print them in reverse order with a space between them.

In [ ]:
def reversethestring():
    first_name=input('Enter your first name')
    last_name=input('Enter your last name')
    return last_name[::-1],first_name[::-1]

In [ ]:
reversethestring()

In [ ]:
## Another way 
f_name = input("Input your First Name : ")
l_name = input("Input your Last Name : ")
print ("Hello  " + l_name + " " + f_name)

6. Write a Python program which accepts a sequence of comma-separated numbers from user and generate a list  with those numbers

In [ ]:
values = input("Input some comma seprated numbers : ")
list1 = values.split(",")
print(list1)

7. Write a Python program to accept a filename from the user and print the extension of that

In [ ]:
file_name=input('Enter the name of file')
a=file_name.split('.')
print(a[1])

8. Write a Python program to display the first and last colors from the following list
color_list = ["yellow","Green","grey" ,"orange"]

In [ ]:
color_list = ["yellow","Green","grey" ,"orange"]
print(color_list[0])
print(color_list[-1])

9. Write a Python program that accepts an integer (n) and computes the value of n+nn+nnn

In [ ]:
x = int(input("Input an integer : "))
n1 = int( "%s" % x )
n2 = int( "%s%s" % (x,x) )
n3 = int( "%s%s%s" % (x,x,x) )
print (n1+n2+n3)

Input an integer : 12
122436

10.Write a program to demonstrate different number data types in Python.

In [ ]:
a=True
b=12
c=34.56
d='Data sciience'
print('The datatype of a is ',type(a))
print('The datatype of b is ',type(b))
print('The datatype of c is ',type(c))
print('The datatype of d is ',type(d))

The datatype of a is  <class 'bool'>
The datatype of b is  <class 'int'>
The datatype of c is  <class 'float'>
The datatype of d is  <class 'str'>

11. Python Program to find sum of array

In [ ]:
def sumofarray(b):
    add=0
    for i in b:
        add=add+i
    return add

In [ ]:
sumofarray(np.array([1,2,3]))

6

12.Write a program to create, concatenate and print a string and
 accessing sub-string from a given string

In [ ]:
s1=input('Enter the first string')
s2=input('Enter the second string')
print('The first string entered is',s1)
print('The second string entered is ',s2)
print('concatenation of two entered string',s1+s2)
print('Substring of s1',s1[1:3])
print('substring of s2',s2[2:3])

Enter the first stringshubhangi
Enter the second stringsakarkar
The first string entered is shubhangi
The second string entered is  sakarkar
concatenation of two entered string shubhangisakarkar
Substring of s1 hu
substring of s2 k

13.Create and explain the working of  tuple.

14.Write a python program to find largest of three numbers.

In [ ]:
num1=float(input('Enter first number'))
num2=float(input('Enter second number'))
num3=float(input('Enter third number'))

if (num1>=num2) and (num1>=num3):
    print('The highest number is',num1)
elif (num2>=num1) and (num2>=num3):
    print('The highest number is ',num2)
else:
    print('The higest number is ',num3)

Enter first number2
Enter second number3
Enter third number5
The higest number is  5.0

15.Write a Python program to convert temperatures to and from Celsius,
 Fahrenheit. [ Formula: c = (f-32)(5/9)]

In [ ]:
temp=float(input('Enter temprature'))
unit=input('Enter unit')

if unit=='C' or unit=='c':
    newtemp=9/5*temp+32
    print('Temprature in ferenhite is',fnewtemp)
elif unit=='F' or unit=='f':
    newtemp=5/9*(temp-32)
    print('Temparture is celsius is',newtemp)
else:
    print('unknown unit passed')

Enter temprature38
Enter unitc
Temprature in ferenhite is 100.4

16. Write a Python program to construct the following pattern, using a
 nested for loop

*
* *
* * *
* * * *
* * * * *
* * * *
* * *
* *
*

In [ ]:
max = 6
for i in range(0,max+1):
    print("* "*i)
for i in range(max+1,0,-1):
    print("* "*i)

*
* *
* * *
* * * *
* * * * *
* * * * * *
* * * * * * *
* * * * * *
* * * * *
* * * *
* * *
* *
*

17.Write a program that accepts the lengths of three sides of a triangle
as inputs. The program output should indicate whether or not the triangle
is a right triangle (Recall from the Pythagorean Theorem that in a right
triangle, the square of one side equals the sum of the squares of the
other two sides).

In [ ]:
base=float(input('Enter the base of triangle:'))
height=float(input('Enter the height of triangle:'))
hypo=float(input('Enter the hypo of triangle:'))
if hypo**2==((base**2)+(height**2)):
    print('Entered dimensions of right angle triangle')
else:
    print('The trianle is not right angled triganle')

Enter the base of triangle:3
Enter the height of triangle:4
Enter the hypo of triangle:5
Entered dimensions of right angle triangle

18. Given a range of the first 10 numbers, Iterate from the start number to the end number, and In each iteration print the sum of the current number and previous number

In [ ]:
def sumofnum(num):
    previousnum=0
    for i in range(num):
        sum=previousnum+i
        print('The current number is:',i ,'Previous numbers:',previousnum,'Sum is:',sum)
        previousnum=i

In [ ]:
sumofnum(20)

The current number is: 0 Previous numbers: 0 Sum is: 0
The current number is: 1 Previous numbers: 0 Sum is: 1
The current number is: 2 Previous numbers: 1 Sum is: 3
The current number is: 3 Previous numbers: 2 Sum is: 5
The current number is: 4 Previous numbers: 3 Sum is: 7
The current number is: 5 Previous numbers: 4 Sum is: 9
The current number is: 6 Previous numbers: 5 Sum is: 11
The current number is: 7 Previous numbers: 6 Sum is: 13
The current number is: 8 Previous numbers: 7 Sum is: 15
The current number is: 9 Previous numbers: 8 Sum is: 17
The current number is: 10 Previous numbers: 9 Sum is: 19
The current number is: 11 Previous numbers: 10 Sum is: 21
The current number is: 12 Previous numbers: 11 Sum is: 23
The current number is: 13 Previous numbers: 12 Sum is: 25
The current number is: 14 Previous numbers: 13 Sum is: 27
The current number is: 15 Previous numbers: 14 Sum is: 29
The current number is: 16 Previous numbers: 15 Sum is: 31
The current number is: 17 Previous numbers: 16 Sum is: 33
The current number is: 18 Previous numbers: 17 Sum is: 35
The current number is: 19 Previous numbers: 18 Sum is: 37

19.Given a string, display only those characters which are present at an even index number.

In [ ]:
def printEveIndexChar(str):
    for i in range(0, len(str)-1, 2):
        print("index[",i,"]", str[i] )

inputStr = "shubhangi" 
print("Orginal String is ", inputStr)

print("Printing only even index chars")
printEveIndexChar(inputStr)

Orginal String is  shubhangi
Printing only even index chars
index[ 0 ] s
index[ 2 ] u
index[ 4 ] h
index[ 6 ] n

20.Return the count of sub-string “Shubhangi” appears in the given string

In [ ]:
str = "Shubhangi is good developer. Shubhangi is a Data Scientist"

In [ ]:
cnt = str.count("Shubhangi")
print(cnt)

2

21.Write a program (function!) that takes a list and returns a new list that contains all the elements of the first list minus all the duplicates.

In [ ]:
## Function to remove duplicates from given list
def listduplicate(x):
    y = []
    for i in x:
        if i not in y:
            y.append(i)
    return y

In [ ]:
listduplicate([1,1,2,3,4,4])

[1, 2, 3, 4]

In [ ]:
#this one uses sets
def v2(x):
    return list(set(x))

In [ ]:
v2([1,1,2])

[1, 2]

22.Print multiplication table of 12 using recursion

In [ ]:
def table(n,i):
    print(n*i)
    i=i+1
    if i<=10:
        table(n,i)

In [ ]:
table(20,1)

20
40
60
80
100
120
140
160
180
200

23. Write a function to calculate area and perimeter of a rectangle.

In [ ]:
def rectangle(a,b):
    print('The area of given rectangle is:' ,a*b)
    print('The perimeter of given rectangle is:',2*(a+b))

In [ ]:
rectangle(12,2)

The area of given rectangle is: 24
The perimeter of given rectangle is: 28

24.Write a function to calculate area and circumference of a circle

In [ ]:
def circle():
    import numpy as np
    radius=float(input('Enter the radius of circle'))
    area=np.pi*radius*radius
    return area

In [ ]:
circle()

Enter the radius of circle4

50.26548245743669

25.Write a function to calculate power of a number raised to other

In [ ]:
def powerof(n,p):
    power=n**p
    return power

In [ ]:
powerof(2,3)

8

26.Write a function to tell user if he/she is able to vote or not.

In [ ]:
age=float(input('Enter your age'))
if age >=18:
    print('You are eligible to vote')
else:
    print('Not eligible to vote')

Enter your age21
You are eligible to vote

27.Write a function “perfect()” that determines if parameter number is a perfect number. Use this function in a program that determines and prints all the perfect numbers between 1 and 1000.
[An integer number is said to be “perfect number” if its factors, including 1(but not the number itself), sum to the number. E.g., 6 is a perfect number because 6=1+2+3].

####

In [ ]:
4 //2

2

In [ ]:

def find_factors(num):
    if num//2 > 2:
        added = False
        for i in range(2,num//2,1):
            if num % i != 0:
                continue
            factors.append(i)
            added = True
            break
        if(added):
            find_factors(int(num//i))
        else:
            factors.append(num)
    else:
        factors.append(num)

In [ ]:
def find_perfect(num):
    factorials = []
    for i in range(1,num//2+1):
        if num%i == 0:
            factorials.append(i)
    if sum(factorials) == num:
        return(True)
    else:
        return(False)

In [ ]:
for i in range(1,10000):
    if find_perfect(i):
        print(i)

6
28
496
8128

In [ ]:
for i in range(1000):
    factors = [1]
    find_factors(i)
    if sum(factors) == i:
        print(i)

6

In [ ]:

fi(28)

[1, 2, 4, 7, 14]

In [ ]:
num = mainNum
factors = []

In [ ]:
def perfect(n):
    sum=0
    for i in range(n,1):
        if n%i == 0:
            sum=sum+i
    if sum==n:
        return True
    else:
        return False

In [ ]:
for i in range(1,1001):
    if perfect(i):
        print(i)

28.Write a function to check if a number is even or not.

In [ ]:
def even():
    n=int(input('Enter the number'))
    if n%2 == 0:
        print('The given number is even')
    else:
        print('Odd number')

In [ ]:
even()

Enter the number3
Odd number

29.Write a function to check if a number is prime or not

In [ ]:
def odd():
    n=int(input('Enter the number'))
    if n%2 != 0:
        print('The given number is odd')
    else:
        print('Even number')

In [ ]:
odd()

Enter the number3
The given number is odd

30.Given a list of numbers, return True if first and last number of a list is same

In [ ]:
def isFirst_And_Last_Same(numberList):
    print("Given list is ", numberList)
    firstElement = numberList[0]
    lastElement = numberList[-1]
    if (firstElement == lastElement):
        return True
    else:
        return False

numList = [10, 20, 30, 40, 10]
print("result is", isFirst_And_Last_Same(numList))

Given list is  [10, 20, 30, 40, 10]
result is True

31. Write a program to check if each word in a string begins with a capital letter?

In [ ]:
print( 'The Hilton'.istitle() ) 
print( 'The dog'.istitle() ) 
print( 'sticky rice'.istitle() )

True
False
False

32. Write a program to Check if a string contains a specific substring

In [ ]:
print( 'plane' in 'The worlds fastest plane' ) #=> True
print( 'car' in 'The worlds fastest plane' ) #=> False

True
False

33. Capitalize the first character of a string

In [ ]:
'florida dolphins'.capitalize()

'Florida dolphins'

34. Reverse the string “hello world”

In [ ]:
''.join(reversed("hello world"))

'dlrow olleh'

35. Remove vowels from a string

In [ ]:
string = 'Hello 1 World 2'
vowels = ('a','e','i','o','u')
''.join([c for c in string if c not in vowels])

'Hll 1 Wrld 2'

36. Iterate through a string Using for Loop.

In [ ]:
h_letters = []

for letter in 'shubhangi':
    h_letters.append(letter)

print(h_letters)

['s', 'h', 'u', 'b', 'h', 'a', 'n', 'g', 'i']

37. Iterate through a string Using List Comprehension

In [ ]:
h_letters = [ letter for letter in 'shubhangi' ]
print( h_letters)

['s', 'h', 'u', 'b', 'h', 'a', 'n', 'g', 'i']

38. Transpose of Matrix using Nested Loops

In [ ]:
transposed = []
matrix = [[1, 2, 3, 4], [4, 5, 6, 8]]

for i in range(len(matrix[0])):
    transposed_row = []

    for row in matrix:
        transposed_row.append(row[i])
    transposed.append(transposed_row)

print(transposed)

[[1, 4], [2, 5], [3, 6], [4, 8]]

39. Write a program to check whether a number is divisible by 7 or not.

In [ ]:
num=int(input("Enter your age"))
if num%7==0:
   print("Number is divisible")
else:
   print("Number is not divisible")

Enter your age33
Number is not divisible

40. Write a program to calculate the electricity bill (accept number of unit from user) according to the following criteria :
             Unit                                                     Price  
First 100 units                                               no charge
Next 100 units                                              Rs 5 per unit
After 200 units                                             Rs 10 per unit
(For example if input unit is 350 than total bill amount is Rs2000)

In [ ]:
amt=0
nu=int(input("Enter number of electric unit"))
if nu<=100:
     amt=0
if nu>100 and nu<=200:
     amt=(nu-100)*5
if nu>200:
     amt=500+(nu-200)*10
print("Amount to pay :",amt)

Enter number of electric unit344
Amount to pay : 1940

41. Write a program to display the last digit of a number.
(hint : any number % 10 will return the last digit)

In [ ]:
num=int(input("Enter any number"))
print("Last digit of number is ",num%10)

Enter any number234
Last digit of number is  4

42. Write a program to check whether an years is leap year or not.

In [ ]:
yr=int(input("Enter the year"))
if yr%100==0:
    if yr%400==0:
          print("Entered year is leap year")
    else:
          print("Entered year is not a leap year")
else:
    if yr%4==0:
         print("Entered year is leap year")  
    else:
        print("Entered year is not a leap year")

Enter the year2008
Entered year is leap year

43. Write a program to accept a number from 1 to 7 and display the name of the day like 1 for Sunday , 2 for Monday and so on.

In [ ]:
num=int(input("Enter any number between 1 to 7 : "))
if num==1:
    print("Sunday")
elif num==2:
    print("Monday")
elif num==3:
    print("Tuesday")
elif num==4:
   print("Wednesday")
elif num==5:
   print("Thursday")
elif num==6:
   print("Friday")
elif num==2:
   print("Saturday")
else:
   print("Please enter number between 1 to 7")

Enter any number between 1 to 7 : 3
Tuesday

44. Write a program to check whether a number entered is three digit number or not.

In [ ]:
num1 = (input("Enter any number"))
l=len(num1)
if l != 3:
     print("Entered number is not 3 digit")
else:
     print("Entered number is 3 digiy and Middle digit is ",(int(num1)%100//10))

Enter any number3
Entered number is not 3 digit

45. Write a program to check whether a number (accepted from user) is positive or negative..

In [ ]:
num1 = int(input("Enter first number"))
if num1 > 0 :
    print("Number is positive")
else:
    print("Number is negative")

Enter first number345
Number is positive

46. Write a program to whether a number (accepted from user) is divisible by 2 and 3 both.

In [ ]:
num1 = int(input("Enter first number"))
if num1%2==0 and num1%3==0:
      print("Number is divisible by 2 and 3 both")
else:
      print("Number is not divisible by both 2 and 3")

Enter first number45
Number is not divisible by both 2 and 3

47. Write a Python program to check the validity of a password (input from users).

Validation :

At least 1 letter between [a-z] and 1 letter between [A-Z].
At least 1 number between [0-9].
At least 1 character from [$#@].
Minimum length 6 characters.
Maximum length 16 characters.

In [ ]:
import re
p= input("Input your password")
x = True
while x:  
    if (len(p)<6 or len(p)>12):
        break
    elif not re.search("[a-z]",p):
        break
    elif not re.search("[0-9]",p):
        break
    elif not re.search("[A-Z]",p):
        break
    elif not re.search("[$#@]",p):
        break
    elif re.search("\s",p):
        break
    else:
        print("Valid Password")
        x=False
        break

if x:
    print("Not a Valid Password")

48. Write a Python program to print alphabet pattern 'A'.

  ***                                                                   
 *   *                                                                  
 *   *                                                                  
 *****                                                                  
 *   *                                                                  
 *   *                                                                  
 *   *

In [ ]:
result_str="";    
for row in range(0,7):    
    for column in range(0,7):     
        if (((column == 1 or column == 5) and row != 0) or ((row == 0 or row == 3) and (column > 1 and column < 5))):    
            result_str=result_str+"*"    
        else:      
            result_str=result_str+" "    
    result_str=result_str+"\n"    
print(result_str)

  ***
 *   *
 *   *
 *****
 *   *
 *   *
 *   *

49. Write a Python program to print alphabet pattern 'G'.

In [ ]:
result_str="";    
for row in range(0,7):    
    for column in range(0,7):     
        if ((column == 1 and row != 0 and row != 6) or ((row == 0 or row == 6) and column > 1 and column < 5) or (row == 3 and column > 2 and column < 6) or (column == 5 and row != 0 and row != 2 and row != 6)):  
            result_str=result_str+"*"    
        else:      
            result_str=result_str+" "    
    result_str=result_str+"\n"    
print(result_str);

  ***
 *   *
 *
 * ***
 *   *
 *   *
  ***

50. Write a Python program to calculate a dog's age in dog's years. Go to the editor
Note: For the first two years, a dog year is equal to 10.5 human years. After that, each dog year equals 4 human years.
Expected Output:

Input a dog's age in human years: 15                                    
The dog's age in dog's years is 73

In [ ]:
h_age = int(input("Input a dog's age in human years: "))

if h_age < 0:
    print("Age must be positive number.")
    exit()
elif h_age <= 2:
    d_age = h_age * 10.5
else:
    d_age = 21 + (h_age - 2)*4

print("The dog's age in dog's years is", d_age)

Input a dog's age in human years: 34
The dog's age in dog's years is 149